import { describe,expect,it } from "vitest";
import { createSensitivityFixture, createSensitivityReport, normalizedDistribution, observeSensitivity, serializeSensitivityReport } from "./sensitivity";

describe("Physarum sensitivity calibration",()=>{
  it("keeps equal paths symmetric and deterministic",()=>{ const fixture=createSensitivityFixture("parallel-corridors",1); expect(observeSensitivity(fixture)).toEqual(observeSensitivity(fixture)); expect(observeSensitivity(fixture).flow.shares.cheap).toBeCloseTo(0.5,8); });
  it("has monotonic cheap-path response to cost ratio",()=>{ const shares=[1,1.005,1.01,1.025,1.05,1.1].map((ratio)=>observeSensitivity(createSensitivityFixture("parallel-corridors",ratio),{maxIterations:1000}).flow.shares.cheap); expect(shares).toEqual([...shares].sort((a,b)=>a-b)); });
  it.each([["hillExponent",[1,1.25,1.5,2,3]],["hillK",[0.1,0.5,1,2,5]],["adaptationRate",[0.5,1,2]],["timeStep",[0.025,0.05,0.1,0.2,0.4]],["initialConductivity",[0.1,0.5,1,2,5]]] as const)("produces finite deterministic %s sweep",(key,values)=>{ for(const value of values){ const overrides={maxIterations:2000,[key]:value}; const first=observeSensitivity(createSensitivityFixture("parallel-corridors"),overrides); expect(first).toEqual(observeSensitivity(createSensitivityFixture("parallel-corridors"),overrides)); expect(Object.values(first.edgeFlows).every(Number.isFinite)).toBe(true); } });
  it("characterizes uniform cost and demand scaling",()=>{ for(const scale of [1,10,100]) expect(observeSensitivity(createSensitivityFixture("parallel-corridors",1.1,1,scale)).flow.dominantShare).toBeGreaterThan(0.5); for(const demand of [0.1,0.5,1,2,5,10]) expect(observeSensitivity(createSensitivityFixture("parallel-corridors",1.1,demand),{maxIterations:2000}).convergence.reason).not.toBe("numericFailure"); });
  it("defines entropy orientation explicitly",()=>{ expect(normalizedDistribution({a:1,b:1})).toMatchObject({normalizedEntropy:1,concentration:0,dominantShare:0.5}); expect(normalizedDistribution({a:1,b:0})).toMatchObject({normalizedEntropy:0,concentration:1,dominantShare:1}); });
  it("generates a deterministic serializable report without wall-clock noise",()=>{ const first=createSensitivityReport(); expect(first).toEqual(createSensitivityReport()); expect(first.observations.length).toBeGreaterThan(40); expect(first.observations.every((item)=>item.runtimeMilliseconds===null)).toBe(true); expect(()=>JSON.parse(serializeSensitivityReport(first))).not.toThrow(); });
  it("does not mutate PreparedNetwork",()=>{ const fixture=createSensitivityFixture("grid"); const before=JSON.stringify(fixture.network); observeSensitivity(fixture); expect(JSON.stringify(fixture.network)).toBe(before); });
});
